version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            venv/bin/pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: download Titanic files from Kaggle
          command: |
            . venv/bin/activate
            venv/bin/pip install kaggle
            export KAGGLE_USERNAME=sharafutdinov
            export KAGGLE_KEY
            echo "{"username":\"${KAGGLE_USERNAME}\","key":\"${KAGGLE_KEY}\}" > kaggle.json
            mkdir ~/.kaggle
            mv kaggle.json ~/.kaggle
            chmod 600 /home/circleci/.kaggle/kaggle.json
            kaggle competitions download titanic

      - run: 
          name: create submission
          command: |
            . venv/bin/activate
            mkdir download_submission
            jupyter nbconvert --execute Titanic.ipynb
            mv submission_1.csv download_submission/submission_1.csv

      - store_artifacts:
          path: download_submission
          destination: download_submission

      - run: 
          name: submit
          command: |
            . venv/bin/activate
            export KAGGLE_USERNAME=sharafutdinov
            export KAGGLE_KEY
            kaggle competitions submit titanic -f download_submission/submission_1.csv -m 'SUBMITTED'
