version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            venv/bin/pip install -r requirements.txt

      - save_cache:
          path:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: create html artifact
          command: |
            . venv/bin/activate
            mkdir html-artifacte-report
            jupyter nbconvert --execute Ex_1.ipynb
            mv Ex_1.html html-artifacte-report/Ex_1.html

      - run:
          name: download Titanic files from Kaggle
          command: |
            . venv/bin/activate
            venv/bin/pip install kaggle
            kaggle competitions download titanic 

      - store_artifacts:
          path: html-artifacte-report
          destination: html-artifacte-report
