version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            venv/bin/pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: create html artifact
          command: |
            . venv/bin/activate
            mkdir html-artifacte-report
            jupyter nbconvert --execute Ex_1.ipynb
            mv Ex_1.html html-artifacte-report/Ex_1.html

      - run:
          name: download Titanic files from Kaggle
          command: |
            . venv/bin/activate
            venv/bin/pip install kaggle
            export KAGGLE_USERNAME=sharafutdinov
            export KAGGLE_KEY
            echo "{"username":\"${KAGGLE_USERNAME}\","key":\"${KAGGLE_KEY}\}" > kaggle.json
            mkdir ~/.kaggle
            mv kaggle.json ~/.kaggle
            kaggle competitions download titanic --file train.csv test.csv 

      - run: 
          name: create submission
          command: |
            . venv/bin/activate
            mkdir download_submission

      - store_artifacts:
          path: html-artifacte-report
          destination: html-artifacte-report
