version: 2
jobs:
  build:
    machine:
      - docker: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies and convert to html
          command: |
            python3 -m venv venv
            . venv/bin/activate
            venv/bin/pip install -r requirements_dev.txt
            mkdir html-artifacte-report
            jupyter nbconvert --execute Ex_1.ipynb
            mv Ex_1.html html-artifacte-report/Ex_1.html

      - store_artifacts:
          path: html-artifacte-report
          destination: html-artifacte-report